apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-3 
  region: eu-central-1
  version: "1.28"
vpc:
  cidr: 10.1.0.0/16
  nat:
    gateway: Disable
managedNodeGroups:
- name: ng-1
  instanceType: t3.medium
  desiredCapacity: 3
  minSize: 3
  maxSize: 5
  taints:
  - key: "node.cilium.io/agent-not-ready"
    value: "true"
    effect: "NoExecute"